server:
  host: "0.0.0.0"
  port: 9999
  max_connections: 100
  conn_timeout: 10m
  time_window: 5m
  min_difficulty: 4
  max_difficulty: 6

client:
  server_address: "server:9999"
  conn_timeout: 10m
  max_nonce: 1000000000
