version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.server
    ports:
      - "9999:9999"
    volumes:
      - ./config.yaml:/app/config.yaml
    restart: unless-stopped
    command: /app/server

  client:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.client
    depends_on:
      - server
    volumes:
      - ./config.yaml:/app/config.yaml
    command: /app/client
    deploy:
      replicas: 10
